# -*- coding: utf-8 -*-
# Traductions FR des noms visibles des mods (occupations, aliments, noms de mods, boutons).
FR = {
    # --- occupations / activités
    "更多互动": "Plus d'interactions",
    "摸鱼": "Glander",
    "写代码LV10": "Coder (niv. 10)",
    "写代码LV20": "Coder (niv. 20)",
    "卷!!": "Se défoncer !!",
    "吃麦当劳": "Manger McDo",
    "发呆ing": "Dans la lune",
    "发呆○": "Rêvasser ○",
    "发呆●": "Rêvasser ●",
    "发呆": "Rêvasser",
    "欢呼ing": "Faire la fête",
    "原版动画扩展-原神启动！": "Animations — Lancement de Genshin !",
    "原神日常": "Genshin au quotidien",
    "原神上班": "Genshin au boulot",
    "\\歌舞应援/": "\\Chant et danse/",
    "\\应援/": "\\Encouragements/",
    "装死": "Faire le mort",
    "在横店演尸体": "Jouer le cadavre à Hengdian",
    "功能增加与强化": "Ajouts et améliorations",
    "休息": "Se reposer",
    "健身": "Faire du sport",
    "练瑜伽": "Faire du yoga",
    "刷视频": "Mater des vidéos",
    "听音乐": "Écouter de la musique",
    "跳舞": "Danser",
    "学习乐器": "Apprendre un instrument",
    "追剧": "Regarder une série",
    "写作业": "Faire ses devoirs",
    "做梦~5lv": "Rêver ~niv.5",
    "做梦~30lv": "Rêver ~niv.30",
    "做梦~60lv": "Rêver ~niv.60",
    "做梦~100lv": "Rêver ~niv.100",
    "做梦~150lv": "Rêver ~niv.150",
    "做梦~200lv": "Rêver ~niv.200",
    "做梦~500lv": "Rêver ~niv.500",
    "玩CS 2": "Jouer à CS 2",
    "玩死亡搁浅": "Jouer à Death Stranding",
    "玩原神": "Jouer à Genshin",
    "玩绝地求生": "Jouer à PUBG",
    "玩永劫无间": "Jouer à Naraka",
    "玩老头环": "Jouer à Elden Ring",
    "玩赛博朋克": "Jouer à Cyberpunk",
    "玩GTA": "Jouer à GTA",
    "玩地平线": "Jouer à Horizon",
    "玩英雄联盟": "Jouer à League of Legends",
    "玩手机": "Sur son téléphone",
    "看直播Only Climb": "Regarder un stream Only Up",
    "做图": "Faire un visuel",
    "写代码": "Coder",
    "做PPT": "Faire un diaporama",
    "网抑云": "Blues du soir",
    "吹风扇": "Devant le ventilateur",
    "吹风扇！": "Devant le ventilateur !",
    "波奇模块": "Module Bocchi",
    "\\摇滚/": "\\Rock/",
    "【动作】叙利亚暑假工": "[Animation] Job d'été galère",
    "做叙利亚暑假工": "Job d'été galère",
    "M1加兰德": "M1 Garand",
    "喂猫": "Nourrir le chat",
    "原版动画扩展-比心心": "Animations — Petit cœur",
    "比心心": "Petit cœur",
    "cos猫娘": "Cosplay fille-chat",
    "扭一扭": "Se trémousser",
    "萌新福音": "Bénédiction du débutant",
    "挂机工作Lv1": "Travail auto (niv. 1)",
    "挂机工作Lv2": "Travail auto (niv. 2)",
    "挂机工作Lv3": "Travail auto (niv. 3)",
    "挂机工作Lv4": "Travail auto (niv. 4)",
    "挂机学习Lv1": "Études auto (niv. 1)",
    "静心打坐": "Méditer",
    "打坐": "Méditation",
    "女仆萝莉斯": "Maxine en soubrette",
    "拖地": "Passer la serpillière",
    "上学": "Aller à l'école",
    "上自习": "Étude en autonomie",
    "抱抱": "Câlin",
    "Cosplay貓娘v2": "Cosplay fille-chat v2",
    "Cosplay貓娘": "Cosplay fille-chat",
    "萝莉丝弹吉他": "Maxine à la guitare",
    "来弹吉他": "Jouer de la guitare",
    "用厌恶的眼神盯着主人": "Te fixer d'un air dégoûté",
    "阴暗地爬行": "Ramper sournoisement",
    "偷看主人": "T'épier",
    "装病": "Faire semblant d'être malade",
    "萝莉斯想陪着你": "Maxine veut te tenir compagnie",
    "想陪着你": "Te tenir compagnie",
    "睡覺(冬天)": "Dormir (hiver)",
    "长时间工作": "Longue journée de travail",
    "写材料": "Rédiger un dossier",
    "冬季温暖小憩": "Sieste au chaud l'hiver",
    "壁炉旁小憩": "Sieste près de la cheminée",
    # --- noms de mods
    "麦门永存！": "Vive McDo !",
    # --- nourriture : McDonald's (noms officiels FR quand ils existent)
    "巨无霸": "Big Mac",
    "汉堡包": "Hamburger",
    "麦辣鸡腿汉堡": "McSpicy",
    "原味板烧鸡腿堡": "Burger au poulet grillé",
    "麦香鸡": "McChicken",
    "麦香鱼": "Filet-O-Fish",
    "吉士汉堡包": "Cheeseburger",
    "双层吉士汉堡": "Double Cheeseburger",
    "不素之霸双层牛堡": "Double Bœuf « Pas végé »",
    "双层深海鳕鱼堡": "Double Filet de cabillaud",
    "安格斯MAX厚牛培根堡": "Angus MAX Bacon",
    "安格斯MAX厚牛芝士堡": "Angus MAX Cheese",
    "双层安格斯MAX厚牛培根堡": "Double Angus MAX Bacon",
    "双层安格斯MAX厚牛芝士堡": "Double Angus MAX Cheese",
    "培根蔬萃双层牛堡": "Double Bœuf Bacon & Légumes",
    "可口可乐": "Coca-Cola",
    "零度可口可乐": "Coca-Cola Zéro",
    "柠檬红茶味饮料": "Thé glacé au citron",
    "雪碧": "Sprite",
    "原味珍珠奶茶": "Bubble tea nature",
    "美汁源阳光橙": "Minute Maid Orange",
    "美汁源100%苹果汁": "Minute Maid 100 % Pomme",
    "优品豆浆": "Lait de soja",
    "纯牛奶（UHT)": "Lait entier (UHT)",
    "热朱古力": "Chocolat chaud",
    "锡兰红茶": "Thé noir de Ceylan",
    "鲜煮咖啡": "Café filtre",
    "冰露包装饮用水": "Eau minérale",
    "薯条": "Frites",
    "麦乐鸡 (5块)": "McNuggets (5 pièces)",
    "玉米杯": "Gobelet de maïs",
    "麦辣鸡翅": "Ailes de poulet épicées",
    "那么大鸡排": "Grand filet de poulet",
    "苹果片": "Quartiers de pomme",
    "麦麦脆汁鸡（琵琶腿）": "Poulet croustillant (pilon)",
    "麦麦脆汁鸡（鸡胸）": "Poulet croustillant (blanc)",
    "三拼小食盒": "Boîte 3 en-cas",
    "人气堡堡桶": "Seau Burgers populaires",
    "炸鸡天团桶": "Seau Poulet frit",
    "麦麦炸鸡桶": "Seau de poulet frit",
    "麦麦汉堡桶": "Seau de burgers",
    "四拼小食桶": "Seau 4 en-cas",
    "圆筒冰淇淋": "Cornet de glace",
    "朱古力新地": "Sundae chocolat",
    "草莓新地": "Sundae fraise",
    "麦旋风™奥利奥原味": "McFlurry™ Oreo nature",
    "麦旋风™奥利奥草莓口味": "McFlurry™ Oreo fraise",
    "香芋派": "Chausson au taro",
    "菠萝派": "Chausson à l'ananas",
    "猪柳麦满分": "McMuffin saucisse",
    "猪柳蛋麦满分": "McMuffin saucisse œuf",
    "双层猪柳蛋麦满分": "Double McMuffin saucisse œuf",
    "吉士蛋麦满分": "McMuffin œuf fromage",
    "火腿扒麦满分": "McMuffin jambon grillé",
    "双层火腿扒麦满分": "Double McMuffin jambon grillé",
    "大脆鸡扒麦满分": "McMuffin poulet croustillant",
    "原味板烧鸡腿麦满分": "McMuffin poulet grillé",
    "双层原味板烧鸡腿麦满分": "Double McMuffin poulet grillé",
    "原味板烧鸡腿炒双蛋堡": "Burger poulet grillé & double œuf",
    "猪柳炒双蛋堡": "Burger saucisse & double œuf",
    "吉士炒双蛋堡": "Burger fromage & double œuf",
    "德式图林根香肠炒双蛋堡": "Burger saucisse de Thuringe & double œuf",
    "火腿扒早安营养卷": "Wrap du matin jambon grillé",
    "图林根香肠早安营养卷": "Wrap du matin saucisse de Thuringe",
    "皮蛋鸡肉粥": "Porridge poulet & œuf de cent ans",
    "雪菜脆笋鸡肉粥": "Porridge poulet, pousses & légumes",
    "脆薯饼": "Galette de pomme de terre",
    "脆香油条": "Beignet croustillant",
    "德式图灵根香肠": "Saucisse de Thuringe",
    "冰奶铁": "Latte glacé",
    "热奶铁": "Latte chaud",
    "冰燕麦奶铁": "Latte avoine glacé",
    "热燕麦奶铁": "Latte avoine chaud",
    "冰厚椰奶铁": "Latte coco glacé",
    "热厚椰奶铁": "Latte coco chaud",
    "冰厚乳奶铁": "Latte crémeux glacé",
    "热厚乳奶铁": "Latte crémeux chaud",
    "冰美式": "Americano glacé",
    "热美式": "Americano chaud",
    "冰焦糖玛奇朵": "Macchiato caramel glacé",
    "热焦糖玛奇朵": "Macchiato caramel chaud",
    "卡布奇诺": "Cappuccino",
    "冰摩卡": "Moka glacé",
    "热摩卡": "Moka chaud",
    "浓缩咖啡": "Expresso",
    "麦咖啡挂耳咖啡": "Café filtre McCafé",
    "冰特浓燕麦巧克力": "Chocolat-avoine intense glacé",
    "热特浓燕麦巧克力": "Chocolat-avoine intense chaud",
    "冰燕麦奶": "Lait d'avoine glacé",
    "热燕麦奶": "Lait d'avoine chaud",
    "冰特浓抹茶牛奶": "Lait matcha intense glacé",
    "热特浓抹茶牛奶": "Lait matcha intense chaud",
    "冰特浓巧克力": "Chocolat intense glacé",
    "热特浓巧克力": "Chocolat intense chaud",
    "热特浓抹茶纯茶": "Thé matcha intense chaud",
    "川宁伯爵红茶": "Thé Earl Grey Twinings",
    "冰牛奶": "Lait glacé",
    "热牛奶": "Lait chaud",
    "特浓抹茶雪冰": "Granité matcha intense",
    "特浓奶香雪冰": "Granité lacté intense",
    "特浓巧克力雪冰": "Granité chocolat intense",
    "芒果雪冰": "Granité mangue",
    "迷你抹茶冰淇淋": "Mini glace matcha",
    "迷你咖啡冰淇淋": "Mini glace café",
    "巧克力马卡龙": "Macaron chocolat",
    "莓果马卡龙": "Macaron fruits rouges",
    "草莓拉明顿": "Lamington fraise",
    "柠檬拉明顿": "Lamington citron",
    "双层吉士1+1随心配菠萝派": "Double Cheese 1+1 + chausson ananas",
    "双层吉士1+1随心配草莓新地": "Double Cheese 1+1 + sundae fraise",
    "双层吉士1+1随心配无糖可口可乐": "Double Cheese 1+1 + Coca Zéro",
    "双层吉士1+1随心配锡兰红茶": "Double Cheese 1+1 + thé de Ceylan",
    "双层吉士1+1随心配香芋派": "Double Cheese 1+1 + chausson taro",
    "双层吉士1+1随心配中可乐": "Double Cheese 1+1 + Coca moyen",
    "双层吉士1+1随心配中雪碧": "Double Cheese 1+1 + Sprite moyen",
    "双层吉士1+1随心配朱古力新地": "Double Cheese 1+1 + sundae chocolat",
    # --- nourriture : autres mods
    "北京烤鸭": "Canard laqué",
    "蛋糕": "Gâteau",
    "每日坚果": "Fruits secs du jour",
    "奥利给": "Biscuits « Allez courage »",
    "零食大礼包": "Grand assortiment de snacks",
    "黑水": "Boisson énergisante noire",
    "奶茶": "Thé au lait",
    "柠檬茶": "Thé au citron",
    "拉非": "Café Lafi",
    "能量棒": "Barre énergétique",
    "蓝鸟功能饮料": "Boisson énergisante Bluebird",
    "vc补充剂": "Complément vitamine C",
    "口曷乐虎": "Boisson tonique « Le Hu »",
    "肾宝": "Tonique « Shenbao »",
    "莲花清温": "Tisane Lianhua",
    "手表": "Montre",
    "香水": "Parfum",
    # --- objets (mod Minecraft)
    "西北风": "Vent d'hiver",
    "末影之眼": "Œil de l'Ender",
    "藏宝图": "Carte au trésor",
    "铁剑": "Épée en fer",
    # --- restants
    "静心打坐_Description": "Un moment de calme pour recentrer son esprit.",
}

# --- noms renommés en anglais par l'outil « codex » (le jeu les charge tels quels)
FR.update({
    "Cheering": "Acclamations",
    "Coding Lv.10": "Coder (niv. 10)",
    "Coding Lv.20": "Coder (niv. 20)",
    "Corpse Role at Hengdian": "Jouer le cadavre à Hengdian",
    "Cosplay Catgirl": "Cosplay fille-chat",
    "Daydreaming ○": "Rêvasser ○",
    "Daydreaming ●": "Rêvasser ●",
    "Fan Breeze": "Devant le ventilateur",
    "Fan Breeze!": "Devant le ventilateur !",
    "Feed the Cat": "Nourrir le chat",
    "Finger Heart": "Petit cœur",
    "Fireside Nap": "Sieste près de la cheminée",
    "Genshin Dailies": "Genshin au quotidien",
    "Genshin Shift": "Genshin au boulot",
    "Genshin Shift Farm": "Genshin : farm",
    "Grind!!": "Se défoncer !!",
    "Hug": "Câlin",
    "Mopping": "Passer la serpillière",
    "Play Dead": "Faire le mort",
    "Slacking Off": "Glander",
    "Stay With You": "Te tenir compagnie",
    "Syrian Summer Job": "Job d'été galère",
    "Warm Winter Nap": "Sieste au chaud l'hiver",
    "Wiggle": "Se trémousser",
    "\Cheer/": "\Chant et danse/",
    "\Rock Out/": "\Rock/",
    "AK-47": "AK-47", "AWP": "AWP", "PPSH-41": "PPSh-41",
    "114": "114", "514": "514",
})
